#!/bin/bash
#
# Argus Edge Installation Fix Script
# Fixes a broken installation by creating missing config and directories
#
# Usage (with the credentials provided):
#   sudo ./fix_installation.sh
#
# This script will:
#   1. Create the missing /etc/argus/config.env with your credentials
#   2. Create the screenshot cache directory with proper permissions
#   3. Install missing Python dependencies (gpxpy)
#   4. Install missing system packages (v4l-utils)
#   5. Fix sudoers for argus user
#   6. Create the .provisioned flag
#   7. Restart all services
#

set -e

# ============ CONFIGURATION ============
# Edit these values for your setup:

TRUCK_TOKEN="truck_6fd92f1349df7e6ca31f8b37048a7c28"
VEHICLE_NUMBER="42"
TEAM_NAME="jones"
CLOUD_URL="http://192.168.0.19"
VEHICLE_CLASS="trophy_truck"

# ============ END CONFIGURATION ============

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

echo ""
echo "=============================================="
echo "  Argus Edge Installation Fix"
echo "=============================================="
echo ""
echo "This will fix your installation with:"
echo "  Vehicle Number: #${VEHICLE_NUMBER}"
echo "  Team Name: ${TEAM_NAME}"
echo "  Cloud URL: ${CLOUD_URL}"
echo "  Truck Token: ${TRUCK_TOKEN:0:20}..."
echo ""
read -p "Press Enter to continue or Ctrl+C to abort..."
echo ""

# Step 1: Create directories
log_info "Step 1: Creating directories..."
mkdir -p /opt/argus/{bin,logs,data,config,provision}
mkdir -p /opt/argus/cache/screenshots
mkdir -p /etc/argus
chown -R argus:argus /opt/argus
chown -R argus:argus /etc/argus
chmod 755 /opt/argus/cache/screenshots
log_success "Directories created"

# Step 2: Create config.env
log_info "Step 2: Creating /etc/argus/config.env..."
cat > /etc/argus/config.env << EOF
# Argus Edge Configuration
# Generated by fix_installation.sh

# Vehicle Identity
ARGUS_VEHICLE_NUMBER=${VEHICLE_NUMBER}
ARGUS_VEHICLE_ID=truck_${VEHICLE_NUMBER}
ARGUS_TEAM_NAME=${TEAM_NAME}
ARGUS_VEHICLE_CLASS=${VEHICLE_CLASS}

# Cloud Server
ARGUS_CLOUD_URL=${CLOUD_URL}
ARGUS_TRUCK_TOKEN=${TRUCK_TOKEN}

# Hardware (auto-detected)
ARGUS_GPS_DEVICE=/dev/argus_gps
ARGUS_CAN_INTERFACE=can0

# Performance
ARGUS_GPS_HZ=10
ARGUS_TELEMETRY_HZ=10
ARGUS_UPLOAD_BATCH_SIZE=50

# Logging
ARGUS_LOG_LEVEL=INFO
EOF
chmod 600 /etc/argus/config.env
chown argus:argus /etc/argus/config.env
log_success "Config file created"

# Step 3: Create provisioned flag
log_info "Step 3: Creating provisioned flag..."
touch /etc/argus/.provisioned
chown argus:argus /etc/argus/.provisioned
log_success "Provisioned flag created"

# Step 4: Install missing system packages
log_info "Step 4: Installing missing system packages..."
if ! command -v v4l2-ctl &> /dev/null; then
    apt-get update -qq
    apt-get install -y -qq v4l-utils
    log_success "v4l-utils installed"
else
    log_success "v4l-utils already installed"
fi

# Step 5: Install missing Python packages
log_info "Step 5: Installing missing Python packages..."
if [[ -f /opt/argus/venv/bin/pip ]]; then
    /opt/argus/venv/bin/pip install --quiet gpxpy httpx 2>/dev/null || true
    log_success "Python packages installed (gpxpy, httpx)"
else
    log_warn "Python venv not found at /opt/argus/venv"
fi

# Step 6: Fix sudoers
log_info "Step 6: Configuring sudoers..."
cat > /etc/sudoers.d/argus << 'EOF'
# Argus Timing System - Allow argus user to manage argus services
argus ALL=(ALL) NOPASSWD: /usr/bin/systemctl enable argus-*
argus ALL=(ALL) NOPASSWD: /usr/bin/systemctl disable argus-*
argus ALL=(ALL) NOPASSWD: /usr/bin/systemctl start argus-*
argus ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop argus-*
argus ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart argus-*
argus ALL=(ALL) NOPASSWD: /usr/bin/systemctl status argus-*
argus ALL=(ALL) NOPASSWD: /usr/bin/journalctl -u argus-*
EOF
chmod 0440 /etc/sudoers.d/argus
chown root:root /etc/sudoers.d/argus
log_success "Sudoers configured"

# Step 7: Stop provisioning service (shouldn't run now that we're provisioned)
log_info "Step 7: Stopping provisioning service..."
systemctl stop argus-provision 2>/dev/null || true
systemctl disable argus-provision 2>/dev/null || true
log_success "Provisioning service stopped"

# Step 8: Restart all services
log_info "Step 8: Restarting services..."
systemctl daemon-reload

for service in argus-gps argus-can argus-uplink argus-ant argus-video; do
    systemctl enable "$service" 2>/dev/null || true
    systemctl restart "$service" 2>/dev/null || true
    status=$(systemctl is-active "$service" 2>/dev/null || echo "inactive")
    if [[ "$status" == "active" ]]; then
        log_success "$service: running"
    else
        log_warn "$service: $status (may need hardware)"
    fi
done

# Dashboard needs special handling - wait a moment for other services
sleep 2
systemctl enable argus-dashboard 2>/dev/null || true
systemctl restart argus-dashboard 2>/dev/null || true
dash_status=$(systemctl is-active argus-dashboard 2>/dev/null || echo "inactive")
if [[ "$dash_status" == "active" ]]; then
    log_success "argus-dashboard: running"
else
    log_warn "argus-dashboard: $dash_status"
fi

# Get IP address
IP=$(hostname -I | awk '{print $1}')

echo ""
echo "=============================================="
echo "  FIX COMPLETE"
echo "=============================================="
echo ""
echo "Dashboard URL: http://${IP}:8080"
echo ""
echo "The dashboard should now be working. On first"
echo "visit, you'll need to set a password through"
echo "the setup wizard."
echo ""
echo "Useful commands:"
echo "  View dashboard logs: journalctl -u argus-dashboard -f"
echo "  View uplink logs:    journalctl -u argus-uplink -f"
echo "  Check all services:  systemctl status 'argus-*'"
echo ""
echo "If cameras still show errors, check:"
echo "  1. Camera is connected: v4l2-ctl --list-devices"
echo "  2. Directory exists: ls -la /opt/argus/cache/screenshots/"
echo ""
